"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Sparkles } from "lucide-react";
import { ParticleBg } from "@/components/fx/ParticleBg";
import { GlassCard } from "@/components/fx/GlassCard";
import { GradientText } from "@/components/fx/GradientText";

export default function LandingPage() {
  return (
    <main className="relative min-h-screen overflow-hidden">
      <ParticleBg density="subtle" />

      <nav className="relative z-10 flex items-center justify-between px-8 py-6">
        <div className="flex items-center gap-2 text-lg font-semibold tracking-tight">
          <Sparkles className="h-5 w-5 text-violet-400" />
          PersonaOn
        </div>
        <Link
          href="/build"
          className="text-sm text-white/70 transition hover:text-white"
        >
          Try the builder →
        </Link>
      </nav>

      <section className="relative z-10 mx-auto flex max-w-5xl flex-col items-center px-6 pt-24 text-center">
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.03] px-3 py-1 text-xs text-white/70">
            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400" />
            AI-native persona generation
          </span>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.05 }}
          className="mt-8 text-balance text-5xl font-semibold leading-[1.05] tracking-tight md:text-7xl"
        >
          Your <GradientText>digital identity,</GradientText>
          <br />
          generated by AI.
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.12 }}
          className="mt-6 max-w-2xl text-balance text-base text-white/60 md:text-lg"
        >
          Answer a handful of questions. Watch an entire personalized profile assemble itself — layout, copy, theme, motion. No templates. No two pages alike.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.2 }}
          className="mt-10 flex flex-wrap items-center justify-center gap-4"
        >
          <Link
            href="/build"
            className="gradient-border group inline-flex items-center gap-2 rounded-full bg-white/[0.04] px-6 py-3 text-sm font-medium text-white transition hover:bg-white/[0.08]"
          >
            Create your persona
            <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
          </Link>
          <Link
            href="/p/sai-deekshith-badam-2"
            className="rounded-full border border-white/10 px-6 py-3 text-sm text-white/70 transition hover:border-white/20 hover:text-white"
          >
            See an example
          </Link>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.3 }}
          className="mt-20 grid w-full grid-cols-1 gap-4 md:grid-cols-3"
        >
          {[
            { title: "Conversational", body: "A short AI dialogue, then your persona is ready." },
            { title: "Adaptive layouts", body: "Bento, magazine, minimal — chosen for who you are." },
            { title: "Persona AI chat", body: "Visitors chat with an AI that knows you." },
          ].map((f) => (
            <GlassCard key={f.title} className="p-6 text-left">
              <div className="text-sm font-semibold tracking-wide text-white/90">{f.title}</div>
              <p className="mt-2 text-sm text-white/55">{f.body}</p>
            </GlassCard>
          ))}
        </motion.div>
      </section>
    </main>
  );
}
