"use client";

import { useBuilder } from "@/lib/store";
import { ShimmerSkeleton } from "@/components/fx/ShimmerSkeleton";
import { PersonaPage } from "@/components/persona/PersonaPage";
import type { Persona } from "@/lib/types";

const PLACEHOLDER: Persona = {
  id: "preview",
  slug: "preview",
  owner_user_id: "preview",
  owner_display_name: "Your Name",
  meta: { purpose: "portfolio", style: "futuristic", palette: "neon", layout_kind: "single-column" },
  hero: {
    headline: "Your persona, generated by AI.",
    subheadline: "Answer a few questions in the panel on the left — this preview updates in real time.",
    cta_label: "Chat",
    ai_chat_position: "none",
  },
  sections: [{ type: "about", priority: 1, content: { body: "Your about section will appear here once you start." } }],
  theme: { primary_color: "#8b5cf6", accent_color: "#22d3ee", mode: "dark", particle_density: "subtle" },
  generated_at: new Date().toISOString(),
  version: 1,
};

function mergePreview(draft: Record<string, unknown>): Persona {
  const d = draft as Partial<Persona>;
  return {
    ...PLACEHOLDER,
    ...d,
    meta: { ...PLACEHOLDER.meta, ...(d.meta ?? {}) },
    hero: { ...PLACEHOLDER.hero, ...(d.hero ?? {}) },
    theme: { ...PLACEHOLDER.theme, ...(d.theme ?? {}) },
    sections: (d.sections as Persona["sections"]) ?? PLACEHOLDER.sections,
  };
}

export function PreviewPanel() {
  const { draftPersona, isStreaming } = useBuilder();
  const preview = mergePreview(draftPersona);
  return (
    <div className="relative h-full overflow-y-auto rounded-2xl border border-white/10 bg-black/40">
      {isStreaming && (
        <div className="absolute inset-x-0 top-0 z-10 p-2">
          <ShimmerSkeleton className="h-1 w-full opacity-60" />
        </div>
      )}
      <PersonaPage persona={preview} />
    </div>
  );
}
